version: '3.5'
services:
  web:
    build: .
    container_name: nengexplorer
    hostname: nengexplorer
    image: nengexplorer
    ports:
      - "3001:3001"
    volumes:
      - "${HOME}/.nengcoin:/root/.nengcoin"
      - "${HOME}/nengexplorerdb:/data/db"
      - "${HOME}/mongo_backup:/mongo_backup"